[project]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = [
    {name = "lorenzopandolfo",email = "lorenzopandolfo2004@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "python-dotenv (>=1.2.1,<2.0.0)",
    "groq (>=1.0.0,<2.0.0)",
    "python-telegram-bot (>=22.6,<23.0)",
    "gspread (>=6.2.1,<7.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[dependency-groups]
dev = [
    "ruff (>=0.15.2,<0.16.0)",
]
